/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author Yanet abigail
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
      
         this.setLocationRelativeTo(null);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quinto = new javax.swing.JLabel();
        Espa = new javax.swing.JButton();
        Geo = new javax.swing.JButton();
        Mate = new javax.swing.JButton();
        Ingles = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(690, 520));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(740, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(740, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(742, 850));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setText("to");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 50, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel2.setText("to");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, 70));

        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4to.PNG"))); // NOI18N
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 200));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primaria.PNG"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 330, 60));

        quinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinco.PNG"))); // NOI18N
        jPanel1.add(quinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        Espa.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        Espa.setText("Español");
        Espa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Espa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspaActionPerformed(evt);
            }
        });
        jPanel1.add(Espa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, 40));

        Geo.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        Geo.setText("Geografia");
        Geo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Geo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeoActionPerformed(evt);
            }
        });
        jPanel1.add(Geo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, 40));

        Mate.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        Mate.setText("Matemáticas");
        Mate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Mate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateActionPerformed(evt);
            }
        });
        jPanel1.add(Mate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 160, 40));

        Ingles.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        Ingles.setText("Inglés");
        Ingles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 150, 40));
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenes.PNG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapiz.PNG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fracc.PNG"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tierra.PNG"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fraccion.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 90, 90));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Boy.PNG"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, 150));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setText("Salir de App");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateActionPerformed
            MatePort mat = new MatePort();
            mat.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_MateActionPerformed

    private void EspaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspaActionPerformed
            EspaPort espa=new EspaPort();
            espa.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_EspaActionPerformed

    private void GeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeoActionPerformed
            Relieve relie=new Relieve();
            relie.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_GeoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //Al preionar este boton se sale completamente de la aplicacion 
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Espa;
    private javax.swing.JButton Geo;
    private javax.swing.JButton Ingles;
    private javax.swing.JButton Mate;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel quinto;
    // End of variables declaration//GEN-END:variables
}
