/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author Yanet abigail
 */
public class PruebaRelieve extends javax.swing.JFrame {

    /**
     * Creates new form PruebaRelieve
     */
    public PruebaRelieve() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMaceta = new javax.swing.JTextField();
        txtSierra = new javax.swing.JTextField();
        txtDepresion = new javax.swing.JTextField();
        txtValle = new javax.swing.JTextField();
        txtColina = new javax.swing.JTextField();
        txtMacizo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRevisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtMaceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 40));

        txtSierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSierraActionPerformed(evt);
            }
        });
        jPanel1.add(txtSierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 110, 40));
        jPanel1.add(txtDepresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 90, 40));
        jPanel1.add(txtValle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 100, 40));
        jPanel1.add(txtColina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 100, 30));
        jPanel1.add(txtMacizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reli.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 328));

        btnRevisa.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        btnRevisa.setText("Verifica");
        btnRevisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRevisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Introduce en el espacio en Blanco el nombre correspondiente a cada uno");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btnRegresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flecha.PNG"))); // NOI18N
        btnRegresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 80, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -6, 830, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSierraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSierraActionPerformed

    private void btnRevisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisaActionPerformed
       
       
    }//GEN-LAST:event_btnRevisaActionPerformed

    private void btnRegresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresaActionPerformed
        //Regresa al menu Principal
        Relieve r= new Relieve();
        r.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaRelieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaRelieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaRelieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaRelieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaRelieve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresa;
    private javax.swing.JButton btnRevisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtColina;
    private javax.swing.JTextField txtDepresion;
    private javax.swing.JTextField txtMaceta;
    private javax.swing.JTextField txtMacizo;
    private javax.swing.JTextField txtSierra;
    private javax.swing.JTextField txtValle;
    // End of variables declaration//GEN-END:variables
}
